# Generated by cucumber-sinatra. (Sat Apr 02 01:39:13 +0200 2011)

$LOAD_PATH << File.expand_path('../../../lib', __FILE__)

ENV['RACK_ENV'] = 'test'

require 'rspec'
require 'rack/test'
require 'capybara'
require 'capybara/cucumber'

require 'ord'

Capybara.app = Ord.app

class OrdWorld
  def app
    Ord.app
  end
  include RSpec::Expectations
  include RSpec::Matchers
  include Rack::Test::Methods
end

World do
  OrdWorld.new
end
